### ISSUE TITLE
Anyone have any Flow definition files for redux-actions (perhaps just partial ones we can build from)?

### ISSUE THREAD

**Issue by faceyspacey** [reduxactions/redux-actions#183]

**Comment by faceyspacey** [comment]
I've created the following module definition for `createAction`:

```
declare module 'redux-actions' {
  declare type ActionType = string

  declare type Action = {
    type: ActionType,
    payload?: any,
    error?: bool,
    meta?: any,
  }

  declare function createAction<T>(
    type: ActionType,
    payloadCreator?: (...args: Array<T>) => any,
    metaCreator?: Function
  ): (...args: Array<T>) => Action
}
```

And I've noticed a major issue I described on StackOverflow:

http://stackoverflow.com/questions/41784525/exported-typed-functions-that-return-functions-should-not-require-the-returned-f


which is that you won't get the benefit of this type definition if you don't type the returned function. So the following won't work:

```
export const selectProfileTab = createAction('SELECT_PROFILE_TAB', (index: number) => {
  playSound()
  return { index }
})
```

but this will:

```
export const selectProfileTab: (index: number) => any = createAction('SELECT_PROFILE_TAB', (index: number) => {
  playSound()
  return { index }
})
```

The first will work if you call `selectProfileTab('someString')` in the same file, i.e. it will produce an error, but in another file it won't work. This is likely because of Flow's requirement that annotations are required at the "boundaries" of modules. But that defeats the whole purpose of having a module definition file for `redux-actions`. Now you gotta type the returned functions of all your action creators?? That's a lot of boilerplate for what should be automatic. Is anyone else experiencing this? It makes me wanna stop using redux-actions and go back to plain jane action creators.

**Comment by faceyspacey** [comment]
Also, here's a version with the `payload` properly parameterized in return types:

```
declare module 'redux-actions' {
  declare type ActionType = string

  declare type Action<P> = {
    type: ActionType,
    payload?: P,
    error?: bool,
    meta?: any,
  }

  declare function createAction<T, P>(
    type: ActionType,
    payloadCreator?: (...args: Array<T>) => P,
    metaCreator?: Function
  ): (...args: Array<T>) => Action<P>
}
```

Here's how you would use it:

```
type Payload = { index: number }

export const selectProfileTab = createAction('SELECT_PROFILE_TAB', (index: number): Payload => {
  return { index }
})
```

**Comment by JulioC** [comment]
I've updated your definition to use a template parameter for the payloadCreator arguments. So far it works better than original.

```js
declare module 'redux-actions' {
  declare type ActionType = string;

  declare type Action<P> = {
    type: ActionType,
    payload?: P,
    error?: bool,
    meta?: any,
  };

  declare function createAction<T, P>(
    type: ActionType,
    payloadCreator?: T => P,
    metaCreator?: Function
  ): T => Action<P>;

  declare type State = any;

  declare function handleActions(
    reducerMap: any,
    defaultState: State
  ): (state: State, action: Action<any>) => State;
}
```

I've also included a (very badly defined) `handleActions`.

**Comment by JulioC** [comment]
I just discovered [flow-typed](https://github.com/flowtype/flow-typed), which contains definitions for most libraries out there, including redux-actions.

**Comment by pepesenaris** [comment]
is anyone gettting `Computed property cannot be assigned with function type` flow errors when using the actions creators as keys?

**Comment by EugeneZ** [comment]
> is anyone gettting Computed property cannot be assigned with function type flow errors when using the actions creators as keys?

@pepesenaris You can call `.toString()` explicitly on the action creator. It's not perfect but until the types are fixed it's good enough.

**Comment by mslipper** [comment]
See #151 - I'm working on this. Let's continue the discussion there.

**Comment by JamieDixon** [comment]
I've just been told about this issue and I think this PR https://github.com/reduxactions/redux-actions/pull/268 might help.
