### ISSUE TITLE
Should i test action creators created by createAction?

### ISSUE THREAD

**Issue by showmeyourhits** [reduxactions/redux-actions#231]
Howdy.

I don't know where else to ask, so i'll ask here:

> Should i test action creators created by `createAction()`?

For example, i want to have action creator, that adds apple to the basket. So i write this code:

```javascript
import {createAction} from 'redux-actions';
import {ADD_APPLE} from 'AppConstants.js';

export const addApple = createAction(
  ADD_APPLE,
  (apple) => ({apple}),
);
```

Should i have tests for it? Something like that:
```javascript
import {addApple} from 'Actions.js';
import {ADD_APPLE} from 'AppConstants.js';

describe('Actions', () => {
  describe('addApple', () => {
    it('should create action with passed data', () => {
      const apple = {kind: 'red', isRipe: true};
      expect(addApple(apple)).toEqual({type: ADD_APPLE, payload: {apple}})
    });
  });
});
```
It seems to me, that this is monkey business: copying and pasting type constants, writing same tests for every action creator (dozens of them in my current projects). But on other side, it seems like right thing to do, if you want **100% test coverage** for your code.

So, should i test them? Or testing reducer function is enough?

***

PS: I'm a novice in redux and novice in testing, just wanna know what big boys doing.

**Comment by timche** [comment]
Imo you should test action creators and your given example is the way to go. You are actually testing if your passed arguments, like `type`, `payload` function and/or `meta` function are working correctly.

**Comment by mslipper** [comment]
This is one of those things that boils down to personal taste. Some folks strive for 100% test coverage, some don't. @timche's answer is correct if you want 100% test coverage.

The goal of having unit tests is to enable quick verification that your code works and allow for less error-prone refactoring. In your case, I recommend asking yourself this question: under what conditions will my tests fail? If the answer is 'whenever I make changes to my code,' then your tests probably aren't very useful even if they improve your coverage numbers. Try expanding the system under test to include other functionality until you feel like you're testing something that won't break whenever you change implementation details.

**Comment by mslipper** [comment]
I'm closing this issue because it's super old, but that doesn't mean the discussion is over. I'll still respond to any further comments.
