### ISSUE TITLE
integration with redux-saga

### ISSUE THREAD

**Issue by Limycuk** [reduxactions/redux-actions#248]
Hello,
i have redux-actions and redux-saga in one project
I tried to find way get string constant of action for saga subscription.
Could you help me?

**Comment by yangmillstheory** [comment]
We don't support redux-saga, which is entirely different middleware. 

I'm not sure what the use case is, but I think I'd advise standardizing on one middleware in your project; I've never a project that use both simultaneously, they have completely different philosophies and styles.

**Comment by satispunk** [comment]
@yangmillstheory hi, your post confused me. What are those philosophies and styles?

IMO you can use sagas as side effect handlers and redux-actions to do other boilerplate stuff

**Comment by JeromeFranco** [comment]
I agree with @satispunk . They may have different philosophies, but these are philosophies that you would normally use together in your application. One that handles side-effect and one that handles state.

**Comment by JeromeFranco** [comment]
For those who are still looking for an answer to this issue, basically you could call ``.toStrong()`` on your action creator and it will return the action type. 

For example:
```javascript
import { createAction } from 'redux-actions';

const getUserRequest = createAction('GET_USER_REQUEST');

// in your saga
function* getUserSaga({ payload }) { 
// side-effect 
}

takeLatest(getUserRequest.toString(), getUserSaga);
