### ISSUE TITLE
Looking for maintainers!

### ISSUE THREAD

**Issue by timche** [reduxactions/redux-actions#251]
Last year @yangmillstheory and I have jumped on this library to maintain and improve it, but since then, our activity has lowered due to other priorities or interests, so we don't work that much on this project anymore like we did in the past.

- Currently we have several open issues and pull requests which need to be handled.
- A new major version could be released that rewrites and improves the library and adds types for Flowtype and Typescript.

It would be great if we can find 2-3 new maintainers. If you are interested in maintaining this library, don't hesitate and give us a sign in this issue. You should also be able to work independently and with others as well. Of course @yangmillstheory and I will try to help as much as possible when needed.

**Comment by hendrul** [comment]
I'm interested

**Comment by mraerino** [comment]
Could be wise to add a note about this in the Readme.

**Comment by timche** [comment]
Thanks for the suggestion @mraerino.

@hendrul we'll come back to you asap!

**Comment by hendrul** [comment]
Ok I'll wait

**Comment by yangmillstheory** [comment]
Something else that should happen, and is pretty important, is moving the documentation site to be owned by this org (reduxactions). Write now I believe it's still under @vinnymac's Gitbook account which is a bit of a risk.

**Comment by nimish-gupta** [comment]
I'm interested,

**Comment by timche** [comment]
Thanks @nimish-gupta! I'll invite you two @hendrul and @nimish-gupta to the organisation.

**Comment by timche** [comment]
@nimish-gupta and @hendrul. I've sent you an invite to access this repository. Please check your inboxes.

**Comment by hendrul** [comment]
@timche I haven't received the email

**Comment by timche** [comment]
Please check https://github.com/reduxactions/redux-actions/invitations

**Comment by hendrul** [comment]
Ok ready! what else?

**Comment by zaidchauhan** [comment]
@timche Do you still require volunteer?

**Comment by mslipper** [comment]
Happy to join in as well. Let me know.

**Comment by timche** [comment]
Sure @mslipper & @zaidchauhan! I'll invite you.

@mslipper would you mind if you could take over bit of a "lead role"?

**Comment by mslipper** [comment]
@timche sure! Happy to do that. Will ping you with questions & permissions.

**Comment by michaelfriedman** [comment]
If you still need help, I'm willing.

**Comment by timche** [comment]
@mslipper how are things going so far? @hendrul @zaidchauhan are you still available?

**Comment by zchauhan** [comment]
@timche Yes, I am available.

**Comment by zaidchauhan** [comment]
@timeche Yes, I am available


-----------------
Regards
Zaid Chauhan
Sr. Software Engineer

View My Profile on Linked In <http://in.linkedin.com/in/zaidchauhan>

**Comment by michaelfriedman** [comment]
Yes sir, I’d be happy to put in some time. What could you use help with the most?

--

**Comment by timche** [comment]
I think it would be helpful if you guys could connect somehow to organise.

Do you have Slack or Discord?

**Comment by michaelfriedman** [comment]
I have both, do you have a channel or need to set one up?

--

**Comment by mslipper** [comment]
@timche I'm putting together a roadmap to determine where to take the framework next. Rather than Slack and Discord, might I suggest Gitter? Should be easy enough to create one.

**Comment by michaelfriedman** [comment]
Works for me!

--

**Comment by timche** [comment]
I've created a room on Gitter: https://gitter.im/redux-actions/Lobby

**Comment by timche** [comment]
If there is anything urgent, you can contact me via email. Thank you guys for taking over!

**Comment by budaaaa** [comment]
@timche I would like to contribute also if thats possible!

**Comment by hendrul** [comment]
Available to help!

2018-01-11 10:49 GMT-04:00 Tim Cheung <notifications@github.com>:

**Comment by larkintuckerllc** [comment]
First, having written a fair amount of Redux code, I added redux-actions to my projects quite awhile ago (not a fundamental game changer, but more of an incremental benefit).  I have been "preaching" it's use in my development circles and continue to believe that it adds value; have a vested interest in ensuring it (or something like it) continues to exist.

What I believe that I can bring to the table is documentation skills; I actually have a large body of documentation on all things JavaScript (including an article on redux-actions that could be reworked).

https://medium.com/@johntucker_48673
https://medium.com/front-end-hacking/removing-boilerplate-with-redux-actions-e283737996b6

Let me know if you see a need that I can fill.  I tend to have about 10 hours a week of spare time (right now spent mostly of writing on Medium).

**Comment by timche** [comment]
@mslipper ⬆️

**Comment by mslipper** [comment]
@larkintuckerllc awesome! Can you own the documentation side of the project? I'm not sure how up-to-date the existing docs are. If you could review them and update them as necessary, I'd really appreciate it.

**Comment by larkintuckerllc** [comment]
@mslipper Yes. I will start a review of the existing documentation this week and give feedback. Will want to know how you want to share information on this focused topic (assume not here; maybe in a issue?).

**Comment by mslipper** [comment]
An issue would be great.

**Comment by wuweiweiwu** [comment]
@timche Is it too late to join? I was planning to start picking up some issues :)

**Comment by osmangoninahid** [comment]
Interested

**Comment by xaiki** [comment]
this seems to be solved, link to this issue should probably be removed from README ?
