### ISSUE TITLE
LICENSING issue

### ISSUE THREAD

**Issue by char0n** [reduxactions/redux-actions#273]
Hi,

I'm big fan of this library, but recently come into environment where legal stuff and licensing is very much part of development process. I found out that one the dependencies that `redux-actions` is using is not properly licensed. The dependency in question is [reduce-reducers](https://github.com/acdlite/reduce-reducers). This dependency states that is licensed under MIT but doesn't have any license file in repository not in npm package. Can this be somehow remedied on this package ? I have already issued a [PR](https://github.com/acdlite/reduce-reducers/pull/10) on `reduce-reducers` repo with proper license file, but there is not response there. 

Thank you very much

**Comment by timche** [comment]
I reached out to @acdlite privately. Let's see if we can resolve this somehow, but unfortunately it's not possible on our side.

**Comment by timche** [comment]
We (`redux-utilities` organisation) now have access to the repository.
